# docker compose with postgresql
version: '3.1'
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${BACKEND_DB_USER}
      POSTGRES_PASSWORD: ${BACKEND_DB_PASSWORD}
      POSTGRES_DB: ${BACKEND_DB_NAME}
    ports:
      - "${BACKEND_DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    user: postgres
    privileged: false
volumes:
  pgdata: