name: Continuous Integration

# This action works with pull requests and pushes
on:
  push:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify client code
        uses: creyD/prettier_action@v4.3
        with:
          working_directory: ${GITHUB_WORKSPACE}/src/client
          same_commit: true
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{ts,tsx}
      - name: Prettify server code
        uses: creyD/prettier_action@v4.3
        with:
          working_directory: ${GITHUB_WORKSPACE}/src/server
          same_commit: true
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{ts,tsx}
